name: coverity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: cd
      run: ls
    - name: configure
      run: ./configure
    - name: make
      run: make -j8
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
