name: coverity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: autoreconf && ./configure
    - name: make clean
      run: make clean
    - name: coverity configure
      run: cov-configure --gcc && cov-configure --compiler cc --comptype gcc --template
    - name: coverity build
      run: cov-build --dir idir make -j8
    - name: coverity analyze
      run: cov-analyze --dir idir --enable-constraint-fpp --enable-virtual --enable-fnptr -s `pwd` --all
    - name: coverity commit
      run: cov-commit-defects --dir idir --host localhost --port 18080 --user admin --password coverity --stream openssh
      
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
