name: coverity

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  coverity:
    environment: COVERITY
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    #- name: configure
    #  run: autoreconf && ./configure
    #- name: make clean
    #  run: make clean
    - name: Coverity Conventional Workflow
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        autoreconf && ./configure
        make clean
        cov-configure --gcc && cov-configure --compiler cc --comptype gcc --template
        cov-build --dir idir make -j8
        cov-analyze --dir idir --enable-constraint-fpp --enable-virtual --enable-fnptr -s `pwd` --all
        cov-commit-defects --dir idir --url ${{ vars.COV_URL }} --user ${{ secrets.COV_USER }} --password ${{ secrets.COV_PASSPHRASE }} --stream openssh

      
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
