name: coverity

on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  coverity:
    environment: COVERITY
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
    - name: Get changed files
      id: changed-files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
        else
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
        fi        
    - name: List changed files
    run: |
      for file in ${{ steps.changed-files.outputs.changed_files }}; do
        echo "$file was changed"
      done        
    #- name: configure
    #  run: autoreconf && ./configure
    #- name: make clean
    #  run: make clean
    - name: Coverity Conventional Workflow
      if: ${{ github.event_name != 'pull_request' && github.event_name != 'workflow_dispatch' }}
      run: |
        autoreconf && ./configure
        make clean
        cov-configure --gcc && cov-configure --compiler cc --comptype gcc --template
        cov-build --dir idir make -j8
        cov-analyze --dir idir --enable-constraint-fpp --enable-virtual --enable-fnptr -s `pwd` --all
        cov-commit-defects --dir idir --url ${{ vars.COV_URL }} --user ${{ secrets.COV_USER }} --password ${{ secrets.COV_PASSPHRASE }} --stream openssh
        
    - name: Coverity Desktop / PR / Incremental Workflow
      if: ${{ github.event_name != 'pull_request' && github.event_name != 'workflow_dispatch' }}
      run: |
        autoreconf && ./configure
        make clean
        cov-configure --gcc && cov-configure --compiler cc --comptype gcc --template
        cov-build --dir idir make -j8
        cov-analyze --dir idir --enable-constraint-fpp --enable-virtual --enable-fnptr -s `pwd` --all
        cov-commit-defects --dir idir --url ${{ vars.COV_URL }} --user ${{ secrets.COV_USER }} --password ${{ secrets.COV_PASSPHRASE }} --stream openssh

      
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
