name: coverity

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    environment: COVERITY
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: autoreconf && ./configure
    - name: make clean
      run: make clean
    - name: Coverity Scan
      uses: synopsys-sig/synopsys-action@v1.13.0
      with:
        coverity_url: ${{ vars.COVERITY_NGROK_URL }}
        coverity_user: ${{ secrets.COV_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
        coverity_policy_view: ${{ github.event_name != 'pull_request' && 'Outstanding Issues' || '' }}
        coverity_prComment_enabled: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        coverity_local: true
        include_diagnostics: true
