name: install-coverity-analysis

on:
  workflow_dispatch:
jobs:
  coverity:
    environment: COVERITY
    runs-on: self-hosted

    steps:
    - name: Install Coverity Analysis
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        curl -u ${{ secrets.SNPS_DOCKER_REPO_USER }}:${{ secrets.SNPS_DOCKER_REPO_PASS }} https://sig-repo.synopsys.com/artifactory/coverity-releases/2024.9.1/cov-analysis-linux64-2024.9.1.tar.gz -o cov-analysis-linux64-2024.9.1.tar.gz
        mkdir -p /opt/coverity/cov-analysis/2024.9.1
        mv cov-analysis-linux64-2024.9.1.tar.gz /opt/coverity/cov-analysis/2024.9.1/
        tar zxvf /opt/coverity/cov-analysis/2024.9.1/cov-analysis-linux64-2024.9.1.tar.gz    
