name: install-coverity-analysis

on:
  workflow_dispatch:
jobs:
  coverity:
    environment: COVERITY
    runs-on: self-hosted

    steps:
    - name: Install Coverity Analysis
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        DIR=/tmp/coverity/cov-analysis/cov-analysis-linux64-2024.9.1/
        if [ ! -d "$DIR" ]; then
          mkdir -p /tmp/coverity/cov-analysis
          #curl -u ${{ secrets.SNPS_DOCKER_REPO_USER }}:${{ secrets.SNPS_DOCKER_REPO_PASS }} https://sig-repo.synopsys.com/artifactory/coverity-releases/2024.9.1/cov-analysis-linux64-2024.9.1.tar.gz -o /tmp/coverity/cov-analysis/cov-analysis-linux64-2024.9.1.tar.gz
          cd /tmp/coverity/cov-analysis/
          tar zxvf cov-analysis-linux64-2024.9.1.tar.gz
          cp license.dat /tmp/coverity/cov-analysis/cov-analysis-linux64-2024.9.1/bin           
        fi  
            
